### ISSUE TITLE
Failed to activate the smart-quotes-plus package

### ISSUE THREAD

**Issue by pjv** [blakegarretson/smart-quotes-plus#3]
[Enter steps to reproduce below:]

1. update atom to 0.196
2. launch atom

![2015-05-01 at 8 23 am](https://cloud.githubusercontent.com/assets/327716/7430632/6dafcb6a-efdb-11e4-82a8-3a7d6fa978ff.png)

**Atom Version**: 0.196.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [smart-quotes-plus](https://github.com/blakegarretson/smart-quotes-plus) package, v1.2.0

### Stack Trace

Failed to activate the smart-quotes-plus package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (/Users/pjv/.atom/packages/smart-quotes-plus/lib/smart-quotes-plus.coffee:4:32)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:222:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:203:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:147:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:195:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:434:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:418:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:413:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:394:46)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "mobile-preview",
      "metrics",
      "autosave",
      "autocomplete",
      "symbols-view",
      "project-manager",
      "archive-view",
      "autoflow",
      "background-tips",
      "bookmarks",
      "color-picker",
      "merge-conflicts",
      "spell-check",
      "styleguide",
      "Stylus",
      "atom-ctags",
      "language-generic-config",
      "error-status",
      "atom-color-highlight",
      "markdown-format",
      "atom-handlebars",
      "compare-files",
      "editorconfig",
      "linter-handlebars",
      "prefixr",
      "coffee-lint",
      "coffee-navigator"
    ],
    "themes": [
      "one-dark-ui",
      "pjvish-syntax"
    ],
    "projectHome": "/Users/pjv/development/projects"
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.2.3
assign-align, v0.1.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.12.1
autocomplete-plus-python-jedi, v0.2.7
autocomplete-snippets, v1.3.0
coffee-porter, v0.1.0
css-color-highlighting, v0.2.4
emmet, v2.3.8
file-icons, v1.5.4
goto, v1.7.0
html-entities, v0.3.1
indentation-indicator, v0.4.1
language-nginx, v0.5.2
language-stylus, v0.1.0
linter, v0.12.1
linter-coffeelint, v0.2.1
linter-jshint, v0.1.2
linter-php, v0.0.12
permute, v0.1.0
pjvish-syntax, v0.1.0
simple-drag-drop-text, v0.2.2
slash-closer, v0.7.1
smart-quotes-plus, v1.2.0
space-tab, v0.1.0

# Dev
language-less, v0.24.0
```

**Comment by blakegarretson** [comment]
The deprecated calls and syntax have all been updated, and everything should work fine on Atom 1.0.
